# Assignment: Data Wrangling
## `! git clone https://github.com/DS3001/wrangling`
## Do Q2, and one of Q1 or Q3.

In [1]:
! git clone https://github.com/DS3001/wrangling

Cloning into 'wrangling'...
remote: Enumerating objects: 92, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 92 (delta 42), reused 18 (delta 18), pack-reused 40 (from 1)
Receiving objects: 100% (92/92), 18.08 MiB | 4.64 MiB/s, done.
Resolving deltas: 100% (43/43), done.
Updating files: 100% (21/21), done.

**Q1.** Open the "tidy_data.pdf" document in the repo, which is a paper called Tidy Data by Hadley Wickham.

  1. Read the abstract. What is this paper about?

  This paper is about how to make data cleaning easy and effective through a technique called data tidying. This framework involves using tools to have a consistent data structure when cleaning.

  2. Read the introduction. What is the "tidy data standard" intended to accomplish?

  The "tidy data standard" is intended to make initial exploration and analysis of data more efficient, as well as to simplify the development of data analysis tools that can work well together.

  3. Read the intro to section 2. What does this sentence mean: "Like families, tidy datasets are all alike but every messy dataset is messy in its own way." What does this sentence mean: "For a given dataset, itâ€™s usually easy to figure out what are observations and what are variables, but it is surprisingly difficult to precisely define variables and observations in general."

  The first sentence means that while all tidy datasets have the same structure (variables as columns, observations as rows, etc), messy datasets are all different because their data represents different observations and are often structured differently due to their differing sources.

  The second sentence means that it can be difficult to decide how best to measure or specifically define variables and observations more generally because of the context of the outside world that gives these aspects of datasets a greater meaning.


  4. Read Section 2.2. How does Wickham define values, variables, and observations?

  Wickham defines values as numbers (if quantitative) or as strings (if qualitative). He defines variables as containing all values that measure the same underlying attribute across units. He defines observations as containing all values measured on the same unit across attributes.

  5. How is "Tidy Data" defined in section 2.3?

  "Tidy Data" is defined as a standard way of mapping the meaning of a dataset to its structure.

  6. Read the intro to Section 3 and Section 3.1. What are the 5 most common problems with messy datasets? Why are the data in Table 4 messy? What is "melting" a dataset?

  The five most common problems with messy data sets are column headers are values (not variable names), multiple variables are stored in one column, variables are stored in both rows and columns, multiple types of observational units are stored in the same table, and a single observational unit is stored in multiple tables.

  The data in Table 4 are messy because the column headers are values (not variable names) and there are variables stored in both rows and columns.

  "Melting" a dataset is stacking it in order to turn columns into rows.


  7. Why, specifically, is table 11 messy but table 12 tidy and "molten"?

  Table 11 is messy because it has variables in both rows and columns and the element column is not a variable (instead it has the names of variables).

  Table 12 is more tidy because the dataset is melted and then casted (unstacked) so that the variables aren't in both columns and rows.

  8. Read Section 6. What is the "chicken-and-egg" problem with focusing on tidy data? What does Wickham hope happens in the future with further work on the subject of data wrangling?

  The "chicken-and-egg" problem is that if tidy data is only as useful as the tools that work with it, then tidy tools will continue to be linked to tidy data.

  Wickham hopes that in the future, other frameworks will be developed to make the many other tasks that are involved in data cleaning easier (such as parsing dates and numbers, identifying missing values, etc).

**Q2.** This question provides some practice cleaning variables which have common problems.
1. Numeric variable: For `./data/airbnb_hw.csv`, clean the `Price` variable as well as you can, and explain the choices you make. How many missing values do you end up with? (Hint: What happens to the formatting when a price goes over 999 dollars, say from 675 to 1,112?)
2. Categorical variable: For the `./data/sharks.csv` data covered in the lecture, clean the "Type" variable as well as you can, and explain the choices you make.
3. Dummy variable: For the pretrial data covered in the lecture, clean the `WhetherDefendantWasReleasedPretrial` variable as well as you can, and, in particular, replace missing values with `np.nan`.
4. Missing values, not at random: For the pretrial data covered in the lecture, clean the `ImposedSentenceAllChargeInContactEvent` variable as well as you can, and explain the choices you make. (Hint: Look at the `SentenceTypeAllChargesAtConvictionInContactEvent` variable.)

In [3]:
import pandas as pd

In [ ]:
# 1
airbnb_data = pd.read_csv('wrangling/assignment/data/airbnb_hw.csv')
airbnb_data['Price'].replace(',','', regex = True, inplace = True)
airbnb_data['Price'] = airbnb_data['Price'].astype(int)
airbnb_data = airbnb_data[airbnb_data['Price'] < 1000]
airbnb_data.head()

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0

In [ ]:
airbnb_data[airbnb_data['Price'].isnull()]

Empty DataFrame
Columns: [Host Id, Host Since, Name, Neighbourhood , Property Type, Review Scores Rating (bin), Room Type, Zipcode, Beds, Number of Records, Number Of Reviews, Price, Review Scores Rating]
Index: []

To clean the Price variable, I dropped the commas in the sting values and then type-casted the values from strings to integers. I then removed all price values that were greater than 1000, as I was not as interested in seeing Airbnb rentals that cost more than $1000 per night. After removing these values, I was left with 0 missing values for the Price variable.

In [30]:
# 2
sharks_data = pd.read_csv('wrangling/assignment/data/sharks.csv')
sharks_data['Type'].replace(['Invalid', 'Questionable','Unconfirmed','Unverified','Under investigation'],np.nan)
sharks_data['Type'].mask(sharks_data['Type'] == 'Boating' ,'Boat', inplace=True)
sharks_data

<ipython-input-30-8eec862fc022>:2: DtypeWarning: Columns (10,17,18,19,20,21,24) have mixed types. Specify dtype option on import or set low_memory=False.
  sharks_data = pd.read_csv('wrangling/assignment/data/sharks.csv')

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,0,2020.02.05,05-Feb-2020,2020.0,Unprovoked,USA,Maui,NaN,Stand-Up Paddle boarding,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2020.01.30.R,Reported 30-Jan-2020,2020.0,Provoked,BAHAMAS,Exumas,NaN,Floating,Ana Bruna Avila,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2020.01.17,17-Jan-2020,2020.0,Unprovoked,AUSTRALIA,New South Wales,Windang Beach,Surfing,Will Schroeter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2020.01.16,16-Jan-2020,2020.0,Unprovoked,NEW ZEALAND,Southland,Oreti Beach,Surfing,Jordan King,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2020.01.13,13-Jan-2020,2020.0,Unprovoked,USA,North Carolina,"Rodanthe, Dare County",Surfing,Samuel Horne,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6457,6457,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6458,6458,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6459,6459,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6460,6460,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ÂºN, 79ÂºW",NaN,Jules Patterson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6461,6461,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

To clean the "Type" variable, I replaced the "Invalid", "Questionable", "Unconfirmed", "Unverified", and "Under investigation" values with np.nan and replaced the "Boating" values with "Boat" so that there was only one category for incidents involving boats. I did this to consolidate the "Type" of incidents to "Provoked", "Unprovoked", "Sea Disaster", "Boat", and "Watercraft" since I felt that these categories provided the most concise information in this context.

In [25]:
# 3
import numpy as np
pretrial_data = pd.read_parquet('wrangling/data/justice_data.parquet')
pretrial_data['WhetherDefendantWasReleasedPretrial'].replace(9, np.nan, inplace = True)
pretrial_data

,InternalStudyID,REQ_REC#,Defendant_Sex,Defendant_Race,Defendant_BirthYear,Defendant_Age,Defendant_AgeGroup,Defendant_AgeatCurrentArrest,Defendant_AttorneyTypeAtCaseClosure,Defendant_IndigencyStatus,...,NewFelonySexualAssaultArrest_OffDate,NewFelonySexualAssaultArrest_ArrestDate,NewFelonySexualAssaultArrest_DaysBetweenContactEventandOffDate,NewFelonySexualAssaultArrest_DaysBetweenOffDateandArrestDate,NewFelonySexualAssaultArrest_DaysBetweenReleaseDateandOffDate,NewFelonySexualAssaultArrest_Disposition,Intertnalindicator_ReasonforExcludingFromFollowUpAnalysis,CriminalHistoryRecordsReturnedorCMSRecordsFoundforIndividual,DispRecordFoundforChargesinOct2017Contact_Atleast1dispfound,CrimeCommission2021ReportClassificationofDefendants
0,ADI00001,1,M,W,1986,31,3,31,99,99,...,,,,999,999,,4,1,0,Defendant could not be classified or tracked d...
1,ADI00007,3,M,B,1956,60,6,60,9,9,...,,,,999,999,,5,1,1,Defendant Detained Entire Pre-Trial Period_Und...
2,ADI00008,4,M,W,1990,27,3,27,9,9,...,,,,999,999,,5,1,1,Defendant Detained Entire Pre-Trial Period_Und...
3,CDI00036,6,M,B,1989,27,3,27,0,0,...,,,,999,999,,5,1,1,Defendant Detained Entire Pre-Trial Period_Und...
4,CDI00038,7,F,W,1988,28,3,28,0,0,...,,,,999,999,,0,1,1,New criminal offense punishable by incarcerati...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22981,SJA00343,22839,M,B,1976,41,4,41,2,1,...,,,,999,999,,0,1,1,New criminal offense punishable by incarcerati...
22982,SJA00344,,F,W,,,9,,99,99,...,,,,999,999,,3,,9,Defendant could not be classified or tracked d...
22983,SJA00345,22841,M,B,1981,36,4,36,1,1,...,,,,999,999,,0,1,1,New criminal offense punishable by incarcerati...
22984,SJA00346,22842,F,B,1993,24,2,24,5,0,...,,,,999,999,,0,1,1,New criminal offense punishable by incarcerati...
22985,SJA00347,22843,M,B,1985,31,3,31,2,1,...,,,,999,999,,0,1,1,New criminal offense punishable by incarcerati...

To clean the WhetherDefendantWasReleasedPretrial variable, I replaced the missing (unclear) values with np.nan.

In [28]:
# 4
pretrial_data['ImposedSentenceAllChargeInContactEvent'].replace('', np.nan, inplace = True)
pretrial_data['ImposedSentenceAllChargeInContactEvent']

0
1                      60
2                      12
3        .985626283367556
4
               ...
22981
22982
22983
22984
22985
Name: ImposedSentenceAllChargeInContactEvent, Length: 22986, dtype: object

**Q3.** Many important datasets contain a race variable, typically limited to a handful of values often including Black, White, Asian, Latino, and Indigenous. This question looks at data gathering efforts on this variable by the U.S. Federal government.

1. How did the most recent US Census gather data on race?
2. Why do we gather these data? What role do these kinds of data play in politics and society? Why does data quality matter?
3. Please provide a constructive criticism of how the Census was conducted: What was done well? What do you think was missing? How should future large scale surveys be adjusted to best reflect the diversity of the population? Could some of the Census' good practices be adopted more widely to gather richer and more useful data?
4. How did the Census gather data on sex and gender? Please provide a similar constructive criticism of their practices.
5. When it comes to cleaning data, what concerns do you have about protected characteristics like sex, gender, sexual identity, or race? What challenges can you imagine arising when there are missing values? What good or bad practices might people adopt, and why?
6. Suppose someone invented an algorithm to impute values for protected characteristics like race, gender, sex, or sexuality. What kinds of concerns would you have?